version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: 'always'
    volumes:
      - ./database/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_TCP_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestdb
      TZ: America/Sao_Paulo

  admin:
    image: phpmyadmin/phpmyadmin:latest
    links:
     - db:db
    depends_on:
     - db
    ports:
     - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: db
      PMA_PORT: 3306

  api:
    container_name: nest_api
    build: 
      context: .
      target: debug
    restart: always
    links:
      - db:db
    depends_on:
      - db
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/home/api
