version: '3.8'

services:
  api:
    container_name: nest_api
    build: 
      context: .
      target: debug
    restart: always
    links:
      - db:${MYSQL_HOST}
    depends_on:
      - db
    ports:
      - "${API_PORT}:${API_PORT}"
      - "9229:9229"
    volumes:
      - .:/home/api

  admin:
    image: phpmyadmin/phpmyadmin:latest
    links:
     - db:${MYSQL_HOST}
    depends_on:
     - db
    ports:
     - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: ${MYSQL_HOST}
      PMA_PORT: ${MYSQL_PORT}

  db:
    image: mysql:5.7
    container_name: ${MYSQL_HOST}
    volumes:
      - ./database/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_TCP_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      TZ: America/Sao_Paulo
